fix(core-card): add prop to disable shadow & enabled by default DJR-3058
telus/tds-core pull request #1508
Opened 2020-11-24 06:46 UTC by mukeshkumarshahi

https://telusdigital.atlassian.net/browse/DJR-3058

2020-12-03 14:59 UTC, jraff requested changes

2020-12-03 15:02 UTC, jraff requested changes

2020-12-03 15:02 UTC, jraff commented on packages/Card/Card.jsx
> +   * @since 2.1.0  added `default`, `defaultWithBorder`, `branded`, `alternative`, `noShadow`.
Please also rename the variant to `defaultOnlyBorder` from `noShadow`

2020-12-03 16:33 UTC, jraff requested changes

2020-12-03 16:33 UTC, jraff commented on packages/Card/Card.md
> +Cards with border `defaultOnlyBorder` variant is to be used to create less visual emphasis than other variants of cards with border or shadow. It also matches the same z-index as other coloured varia
Can we change this to:

> Cards with the `defaultOnlyBorder` variant are to be used to create less visual emphasis than other variants of cards with a border or shadow. It also matches the same z-index as other coloured variant cards without shadow. It should be used near forms, but not containing forms.

2020-12-04 08:13 UTC, swatiTelus commented
Closing, this PR as now duplicate of #1511

2020-12-04 08:13 UTC, closed without merging