DJR-3057 Text button
telus/tds-core pull request #1512
Opened 2020-12-03 18:38 UTC by meeschka

## Related issues

Per [DJR-3057](https://telusdigital.atlassian.net/browse/DJR-3057)

## Description

- Creates the TextButton component, a component that looks like a link but functions like a button

## Checklist before submitting pull request

- [X ] New code is unit tested
- [X] Commits follow our [Developer Guide](https://tds.telus.com/contributing/developer-guide.html#make-a-commit)
- [ ] For code changes, run `npm run prepr` locally
  - make sure visual and accessibility tests pass

2020-12-04 15:41 UTC, jraff requested changes
Can we delete `packages/TextButton/package-lock.json`

2020-12-04 15:41 UTC, jraff commented on packages/TextButton/__tests__/TextButton.spec.jsx
> +// import 'jest-styled-components'
Can we delete this comment.

2020-12-04 18:27 UTC, meeschka commented on packages/TextButton/__tests__/TextButton.spec.jsx
> +// import 'jest-styled-components'
Whoops, sorry about that!

2020-12-08 17:17 UTC, jraff approved these changes

2020-12-08 17:18 UTC, merged