fix(core-terms-and-conditions): use index as key when mapping
telus/tds-core pull request #1557
Opened 2021-04-06 20:05 UTC by kyletsang

## Related issues

See #1485

## Description

Fixes key warning by using an index since `indexedContent` and `nonIndexContent` allows components

## Checklist before submitting pull request

Unfortunately having a number of issues running the environment - gitbook doesn't install.  Hoping this change is minor enough to submit?

2021-04-06 21:13 UTC, kyletsang commented
Unable to update snapshots on my end.  I believe a number of outdated dependencies are causing issues with my version of Node (14)

2021-04-21 14:20 UTC, jraff approved these changes

2021-04-21 14:20 UTC, jraff requested changes
Please fix the unit tests.

2021-04-21 17:33 UTC, jraff approved these changes

2021-04-21 17:33 UTC, merged