Updating designer guide to reflect transition to Figma
telus/tds-core pull request #1637
Opened 2021-11-23 15:54 UTC by donnavitan

## Description
- Providing alert notification to share news of transition to Figma
- Providing public Figma view links to TDS Core libraries and TDS UI sticker sheet
- Providing download links to local .fig Figma files for TDS Core libraries and TDS UI sticker sheet (these links need to be updated once the files are uploaded and links are publicly available)
- Removed references to Sketch, Craft DSM, and Invision

[local-Figma-files.zip](https://github.com/telus/tds-core/files/7589347/local-Figma-files.zip)

2021-11-24 16:31 UTC, jraff approved these changes

2021-11-24 17:31 UTC, jraff requested changes
Commit message needs to follow semver

2021-12-03 15:19 UTC, donnavitan commented
@billtelus @jraff Can I get help on what to do next?

2021-12-03 15:33 UTC, billtelus commented
> @billtelus @jraff Can I get help on what to do next?

I'll handle this :)

2022-07-14 14:42 UTC, closed without merging